### ISSUE TITLE
Solicitud de cambio: Detalles usuario

### ISSUE THREAD

**Issue by julsoutos** [antsuabon/decide-part-andarax-autenticacion-defensa#2]
Se quiere crear un formulario donde el propio usuario (registrado previamente) pueda editar su nombre, apellidos, email y teléfono, sin necesidad de acudir al usuario admin del sistema. Además, esos campos deben estar controlados con sus respectivas restricciones.

**Comment by JulianGR** [comment]
Cerrada después de mergeo a master
