### ISSUE TITLE
Solicitud de cambio: Formulario de detalles usuario

### ISSUE THREAD

**Issue by julsoutos** [antsuabon/decide-part-andarax-autenticacion-defensa#5]
Se pide como cambio que se implemente un formulario para que un usuario previamente implementado en el sistema pueda cambiar su nombre, apellidos, email y teléfono, respetando las mismas restricciones que cuando se registró, todo esto sin necesidad de acudir al admin del sistema.

**Comment by JulianGR** [comment]
Hecha y mergeada
